spring.application.name=helpdesk
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,metrics
management.metrics.tags.application=${spring.application.name}
